version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - ./backend/data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis-service
    image: redis:7.0.5-alpine 
    restart: unless-stopped
    expose:
      - 6379
    depends_on:
      - mongodb

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb
      - redis

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

volumes:
  data:
